### ISSUE TITLE
How to set root node in fpga kernel

### ISSUE THREAD

**Issue by zxhero** [CGCL-codes/ScalaBFS#2]
Hi, I only saw you comment root_node in configuration.scala, but how do you set root node in current frontier?
![image](https://user-images.githubusercontent.com/21699586/130893521-819851c7-fe31-425d-a0db-d71741d9f47f.png)

Thanks!

**Comment by ceciliawinter** [comment]
The root node can be set by setting the preload file of the BRAM that realizes the current frontier.
